# This file contains values from Cookiecutter

default_context:
  project_name: "cutter"
  project_description: "Awesome `cutter` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "soho"
  license: "BSD-3"
  minimal_python_version: 3.9
  github_name: "lgprobert"
  email: "lgprobert@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
